plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.shagunai'
    compileSdk 34

    defaultConfig {
        applicationId "com.shagunai"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {

    implementation "androidx.core:core-ktx:1.13.1"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "com.google.android.material:material:1.12.0"
    implementation "androidx.activity:activity-ktx:1.9.2"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"

    // AI Runtime
    implementation "com.microsoft.onnxruntime:onnxruntime-android:1.22.0"

    // OpenCV (image processing & blending)
    implementation "org.opencv:opencv:4.10.0"

    // Video Processing
    implementation "androidx.media3:media3-transformer:1.4.1"
    implementation "androidx.media3:media3-effect:1.4.1"
    implementation "androidx.media3:media3-common:1.4.1"

    // EXIF support
    implementation "androidx.exifinterface:exifinterface:1.3.7"
}
